dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.index, name="dashboard"),
    path("charts/", views.charts, name="charts"),
    path("widgets/", views.widgets, name="widgets"),
    path("tables/", views.tables, name="tables"),
    path("grid/", views.grid, name="grid"),
    path("form-basic/", views.form_basic, name="form-basic"),
    path("form-wizard/", views.form_wizard, name="form-wizard"),
    path("buttons/", views.buttons, name="buttons"),
    path("icon-material/", views.icon_material, name="icon-material"),
    path("icon-fontawesome/", views.icon_fontawesome, name="icon-fontawesome"),
    path("elements/", views.elements, name="elements"),
    path("gallery/", views.gallery, name="gallery"),
    path("invoice/", views.invoice, name="invoice"),
    path("chat/", views.chat, name="chat"),
]

matrix_admin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls'))
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'dashboard/index.html')


def charts(request):
    return render(request, 'dashboard/charts.html')


def widgets(request):
    return render(request, 'dashboard/widgets.html')




def tables(request):
    return render(request, "dashboard/tables.html")




def grid(request):
    return render(request, "dashboard/grid.html")




def form_basic(request):
    return render(request, "dashboard/form_basic.html")




def form_wizard(request):
    return render(request, "dashboard/form_wizard.html")




def buttons(request):
    return render(request, "dashboard/buttons.html")




def icon_material(request):
    return render(request, "dashboard/icon-material.html")




def icon_fontawesome(request):
    return render(request, "dashboard/icon-fontawesome.html")




def elements(request):
    return render(request, "dashboard/elements.html")




def gallery(request):
    return render(request, "dashboard/gallery.html")





def invoice(request):
    return render(request, "dashboard/invoice.html")



def chat(request):
    return render(request, "dashboard/chat.html")

templates/base.html
{% load static %}

{% block html %}
<!DOCTYPE html>
<html dir="ltr" lang="en">
{% block head %}
   <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}">
    <title>Matrix Template - The Ultimate Multipurpose admin template</title>
                <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/animation.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/asColorPicker.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/fullcalendar.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/calendar.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/dataTables.bootstrap4.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/responsive.bootstrap4.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/fontawesome-all.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/jquery.gritter.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/jquery.minicolors.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/jquery.steps.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/materialdesignicons.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/multicheck.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/perfect-scrollbar.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/quill.core.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/quill.snow.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/select2.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/steps.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/themify-icons.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/toastr.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/weather-icons.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/weather-icons.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/float-chart.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/style.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/custom.css' %}" rel="stylesheet"/>
    <!-- HTML5 Shim and Respond.js' %} IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js' %} doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' %}"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js' %}/1.4.2/respond.min.js' %}"></script>
<![endif]-->
   {% block extra_style %}{% endblock extra_style %}
</head>
{% endblock head %}
   
   {% block body %}
   
       <body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css' %} -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
         {% include 'dashboard/includes/header.html' %}
         {% include 'dashboard/includes/sidebar.html' %}
          <div class="page-wrapper">
           {% block content %}{% endblock content %}
           {% include 'dashboard/includes/footer.html' %}
         </div>
    </div>

    {% block script %}
    
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        <script src="{% static 'js/perfect-scrollbar.jquery.min.js' %}"></script>
        <script src="{% static 'js/sparkline.js' %}"></script>
        <script src="{% static 'js/waves.js' %}"></script>
        <script src="{% static 'js/sidebarmenu.js' %}"></script>
        <script src="{% static 'js/custom.min.js' %}"></script>

        <script src="{% static 'js/excanvas.js' %}"></script>
        <script src="{% static 'js/jquery.flot.js' %}"></script>
        <script src="{% static 'js/jquery.flot.pie.js' %}"></script>
        <script src="{% static 'js/jquery.flot.time.js' %}"></script>
        <script src="{% static 'js/jquery.flot.time.js' %}"></script>
        <script src="{% static 'js/jquery.flot.stack.js' %}"></script>
        <script src="{% static 'js/jquery.flot.crosshair.js' %}"></script>
        <script src="{% static 'js/jquery.flot.tooltip.min.js' %}"></script>
        <script src="{% static 'js/moment.min.js' %}"></script>
        <script src="{% static 'js/chart-page-init.js' %}"></script>
        <script src="{% static 'js/app-style-switcher.js' %}"></script>
        <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
        <script src="{% static 'js/datatable-checkbox-init.js' %}"></script>
        <script src="{% static 'js/datatables.min.js' %}"></script>
        <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
        <script src="{% static 'js/dataTables.responsive.min.js' %}"></script>
        <script src="{% static 'js/responsive.bootstrap4.min.js' %}"></script>
        <script src="{% static 'js/jquery.charts-sparkline.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/jquery-asColor.min.js' %}"></script>
        <script src="{% static 'js/jquery-asGradient.js' %}"></script>
        <script src="{% static 'js/jquery-asColorPicker.min.js' %}"></script>
        <script src="{% static 'js/jquery.minicolors.min.js' %}"></script>
        <script src="{% static 'js/jquery.multicheck.js' %}"></script>
        <script src="{% static 'js/jquery.validate.min.js' %}"></script>
        <script src="{% static 'js/toastr.min.js' %}"></script>
        <script src="{% static 'js/select2.full.min.js' %}"></script>
        <script src="{% static 'js/select2.min.js' %}"></script>
        <script src="{% static 'js/jquery.inputmask.bundle.min.js' %}"></script>
        <script src="{% static 'js/quill.min.js' %}"></script>
        <script src="{% static 'js/mask.init.js' %}"></script>
        <script src="{% static 'js/meg.init.js' %}"></script>
        <script src="{% static 'js/cal-init.js' %}"></script>
        <script src="{% static 'constant/strings.js' %}"></script>
        <script src="{% static 'constant/validator.js' %}"></script>

        <script>
            $(document).ready(function () {
                $('#example').DataTable();
            });
        </script>
        <script>
            $(document).ready(function () {
                $('#zero_config').DataTable();
            });
        </script>

    {% block extra_script %}{% endblock extra_script %}

    
    {% endblock script %}

    </body>
   {% endblock body %}


{% endblock html %}

templates/dashboard/authentication-register.html
<!DOCTYPE html>
<html dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="dashboard/images/favicon.png">
    <title>Matrix Template - The Ultimate Multipurpose admin template</title>
    <!-- Custom CSS -->
    <link href="dashboard/css/style.min.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
    <div class="main-wrapper">
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <div class="preloader">
            <div class="lds-ripple">
                <div class="lds-pos"></div>
                <div class="lds-pos"></div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <div class="auth-wrapper d-flex no-block justify-content-center align-items-center bg-dark">
            <div class="auth-box bg-dark border-top border-secondary">
                <div>
                    <div class="text-center p-t-20 p-b-20">
                        <span class="db"><img src="dashboard/images/logo.png" alt="logo" /></span>
                    </div>
                    <!-- Form -->
                    <form class="form-horizontal m-t-20" action="index.html">
                        <div class="row p-b-30">
                            <div class="col-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text bg-success text-white" id="basic-addon1"><i class="ti-user"></i></span>
                                    </div>
                                    <input type="text" class="form-control form-control-lg" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" required>
                                </div>
                                <!-- email -->
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text bg-danger text-white" id="basic-addon1"><i class="ti-email"></i></span>
                                    </div>
                                    <input type="text" class="form-control form-control-lg" placeholder="Email Address" aria-label="Username" aria-describedby="basic-addon1" required>
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text bg-warning text-white" id="basic-addon2"><i class="ti-pencil"></i></span>
                                    </div>
                                    <input type="text" class="form-control form-control-lg" placeholder="Password" aria-label="Password" aria-describedby="basic-addon1" required>
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text bg-info text-white" id="basic-addon2"><i class="ti-pencil"></i></span>
                                    </div>
                                    <input type="text" class="form-control form-control-lg" placeholder=" Confirm Password" aria-label="Password" aria-describedby="basic-addon1" required>
                                </div>
                            </div>
                        </div>
                        <div class="row border-top border-secondary">
                            <div class="col-12">
                                <div class="form-group">
                                    <div class="p-t-20">
                                        <button class="btn btn-block btn-lg btn-info" type="submit">Sign Up</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper scss in scafholding.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper scss in scafholding.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right Sidebar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right Sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- All Required js -->
    <!-- ============================================================== -->
    <script src="dashboard/js/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="dashboard/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="dashboard/js/bootstrap.min.js"></script>
    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>
    $('[data-toggle="tooltip"]').tooltip();
    $(".preloader").fadeOut();
    </script>
</body>

</html>

templates/dashboard/calendar.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block extra_css %}
    <style xmlns="http://www.w3.org/1999/html">
    </style>
{% endblock %}
{% block page_title %}
 Calender
{% endblock %}
{% block content %}
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">Calendar</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Library</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-body printableArea">
                            <h3><b>INVOICE</b> <span class="pull-right">#5669626</span></h3>
                            <hr>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="pull-left">
                                        <address>
                                            <h3> &nbsp;<b class="text-danger">Material Pro Admin</b></h3>
                                            <p class="text-muted m-l-5">E 104, Dharti-2,
                                                <br> Nr' Viswakarma Temple,
                                                <br> Talaja Road,
                                                <br> Bhavnagar - 364002</p>
                                        </address>
                                    </div>
                                    <div class="pull-right text-right">
                                        <address>
                                            <h3>To,</h3>
                                            <h4 class="font-bold">Gaala &amp; Sons,</h4>
                                            <p class="text-muted m-l-30">E 104, Dharti-2,
                                                <br> Nr' Viswakarma Temple,
                                                <br> Talaja Road,
                                                <br> Bhavnagar - 364002</p>
                                            <p class="m-t-30"><b>Invoice Date :</b> <i class="fa fa-calendar"></i> 23rd
                                                Jan 2018</p>
                                            <p><b>Due Date :</b> <i class="fa fa-calendar"></i> 25th Jan 2018</p>
                                        </address>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="table-responsive m-t-40" style="clear: both;">
                                        <table class="table table-hover">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">#</th>
                                                    <th>Description</th>
                                                    <th class="text-right">Quantity</th>
                                                    <th class="text-right">Unit Cost</th>
                                                    <th class="text-right">Total</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td class="text-center">1</td>
                                                    <td>Milk Powder</td>
                                                    <td class="text-right">2 </td>
                                                    <td class="text-right"> $24 </td>
                                                    <td class="text-right"> $48 </td>
                                                </tr>
                                                <tr>
                                                    <td class="text-center">2</td>
                                                    <td>Air Conditioner</td>
                                                    <td class="text-right"> 3 </td>
                                                    <td class="text-right"> $500 </td>
                                                    <td class="text-right"> $1500 </td>
                                                </tr>
                                                <tr>
                                                    <td class="text-center">3</td>
                                                    <td>RC Cars</td>
                                                    <td class="text-right"> 20 </td>
                                                    <td class="text-right"> %600 </td>
                                                    <td class="text-right"> $12000 </td>
                                                </tr>
                                                <tr>
                                                    <td class="text-center">4</td>
                                                    <td>Down Coat</td>
                                                    <td class="text-right"> 60 </td>
                                                    <td class="text-right">$5 </td>
                                                    <td class="text-right"> $300 </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="pull-right m-t-30 text-right">
                                        <p>Sub - Total amount: $13,848</p>
                                        <p>vat (10%) : $138 </p>
                                        <hr>
                                        <h3><b>Total :</b> $13,986</h3>
                                    </div>
                                    <div class="clearfix"></div>
                                    <hr>
                                    <div class="text-right">
                                        <button class="btn btn-danger" type="submit"> Proceed to payment </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- ============================================================== -->
                <!-- End PAge Content -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Right sidebar -->
                <!-- ============================================================== -->
                <!-- .right-sidebar -->
                <!-- ============================================================== -->
                <!-- End Right sidebar -->
                <!-- ============================================================== -->
            </div>
{% endblock %}

templates/dashboard/includes/footer.html
{% load static %}
  <footer class="footer text-center">
                All Rights Reserved by Matrix-admin. Designed and Developed by <a href="https://wrappixel.com">WrapPixel</a>.
            </footer>

templates/dashboard/includes/sidebar.html
{% load static %}

  <aside class="left-sidebar scrollable ps-container ps-theme-default ps-active-y" data-sidebarbg="skin5">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav" class="p-t-30">
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:dashboard' %}" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">Dashboard</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:charts' %}" aria-expanded="false"><i class="mdi mdi-chart-bar"></i><span class="hide-menu">Charts</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:widgets' %}" aria-expanded="false"><i class="mdi mdi-chart-bubble"></i><span class="hide-menu">Widgets</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:tables' %}" aria-expanded="false"><i class="mdi mdi-border-inside"></i><span class="hide-menu">Tables</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:grid' %}" aria-expanded="false"><i class="mdi mdi-blur-linear"></i><span class="hide-menu">Full Width</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="mdi mdi-receipt"></i><span class="hide-menu">Forms </span></a>
                            <ul aria-expanded="false" class="collapse  first-level">
                                <li class="sidebar-item"><a href="{% url 'dashboard:form-basic' %}" class="sidebar-link"><i class="mdi mdi-note-outline"></i><span class="hide-menu"> Form Basic </span></a></li>
                                <li class="sidebar-item"><a href="{% url 'dashboard:form-wizard' %}" class="sidebar-link"><i class="mdi mdi-note-plus"></i><span class="hide-menu"> Form Wizard </span></a></li>
                            </ul>
                        </li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:buttons' %}" aria-expanded="false"><i class="mdi mdi-relative-scale"></i><span class="hide-menu">Buttons</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="mdi mdi-face"></i><span class="hide-menu">Icons </span></a>
                            <ul aria-expanded="false" class="collapse  first-level">
                                <li class="sidebar-item"><a href="{% url 'dashboard:icon-material' %}" class="sidebar-link"><i class="mdi mdi-emoticon"></i><span class="hide-menu"> Material Icons </span></a></li>
                                <li class="sidebar-item"><a href="{% url 'dashboard:icon-fontawesome' %}" class="sidebar-link"><i class="mdi mdi-emoticon-cool"></i><span class="hide-menu"> Font Awesome Icons </span></a></li>
                            </ul>
                        </li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:elements' %}" aria-expanded="false"><i class="mdi mdi-pencil"></i><span class="hide-menu">Elements</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="mdi mdi-move-resize-variant"></i><span class="hide-menu">Addons </span></a>
                            <ul aria-expanded="false" class="collapse  first-level">
                                <li class="sidebar-item"><a href="{% url 'dashboard:gallery' %}" class="sidebar-link"><i class="mdi mdi-multiplication-box"></i><span class="hide-menu"> Gallery </span></a></li>
                                <li class="sidebar-item"><a href="{% url 'dashboard:invoice' %}" class="sidebar-link"><i class="mdi mdi-bulletin-board"></i><span class="hide-menu"> Invoice </span></a></li>
                                <li class="sidebar-item"><a href="{% url 'dashboard:chat' %}" class="sidebar-link"><i class="mdi mdi-message-outline"></i><span class="hide-menu"> Chat Option </span></a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>